export const ADD_PLACE = 'ADD_PLACE';
export const DELETE_PLACE = 'DELETE_PLACE';

export const SET_PROBLEMS = 'SET_PROBLEMS';
export const PROBLEMS_START_LOADING = 'PROBLEMS_START_LOADING';
export const PROBLEMS_LOAD_ERROR = 'PROBLEMS_LOAD_ERROR';
export const SELECT_GYM = 'SELECT_GYM';

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";